/* @flow */
// Generated by CSS Grid Editor
import styled from 'styled-components'

// prettier-ignore
export default styled.div`
  width: 100%;
  height: 100%;
  display: grid;
  grid-template-columns: 230px 1fr;
  grid-template-rows:
    5vh
    95vh
  ;
  grid-template-areas:
    'menu header'
    'menu content'
  ;
`

export const menu = styled.div`
  background-color: #ddd;
  grid-area: menu;
`

export const header = styled.div`
  background-color: #eee;
  grid-area: header;
`

export const content = styled.div`
  grid-area: content;
`
